spring.application.name=smart-dine-backend

spring.datasource.url=jdbc:mysql://localhost:3306/smart_dine
spring.datasource.username=smartdine_app
spring.datasource.password=SmartDine@2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8081